### ISSUE TITLE
Fails to upload with: `Could not resolve host: null`

### ISSUE THREAD

**Issue by hoijui** [rust-build/rust-build.action#10]
```bash
curl -X POST --data-binary @tmp.zip -H 'Content-Type: application/octet-stream' -H 'Authorization: ***' 'null?name=repvar_null_x86_64-pc-windows-gnu.zip'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: null
```

action run:
https://github.com/hoijui/repvar/runs/3243978118?check_suite_focus=true

the action file:
https://github.com/hoijui/repvar/blob/master/.github/workflows/build.yml

on this note: how do I create a release so this gets triggered?

**Comment by Douile** [comment]
@hoijui it looks likes this failed because it was triggered by a repo push and not a release, so there was no URL for the artifacts to be uploaded to.
To create a release go to the releases tab of your repo.

**Comment by hoijui** [comment]
ahhh ok! :-) makes sense, thanks! :-)
would it be possible for you to build-in a fail-fast/more useful error message for people like me?

**Comment by Douile** [comment]
Yes, i will look into adding that soon
