### ISSUE TITLE
x86_64-apple-darwin is not supported

### ISSUE THREAD

**Issue by joepio** [rust-build/rust-build.action#11]
hi there, thanks for creating this! Unfortunately, it seems like `x86_64-apple-darwin` is not supported. Maybe I'm doing something wrong? Is a specific `runst-on` machine required?

[Workflow yml](https://github.com/joepio/atomic-data-rust/blob/ba2af6ad1974a4ab211b6a71f5dd9d90972187ca/.github/workflows/release.yml#L15)

[Action log](https://github.com/joepio/atomic-data-rust/runs/3320666505?check_suite_focus=true)

**Comment by Douile** [comment]
Darwin is not enabled in a release yet. I've yet to test the produced binaries to confirm it works.

**Comment by joepio** [comment]
Gotcha.

It's mentioned as a supported target in [the readme, though](https://github.com/rust-build/rust-build.action#supported-targets)

**Comment by Douile** [comment]
Yeah that's my bad need to make a dev branch

**Comment by Douile** [comment]
Is now supported in latest release
