### ISSUE TITLE
No binaries in files

### ISSUE THREAD

**Issue by joepio** [rust-build/rust-build.action#12]
Hi there! Thanks for maintaining this.

So I've tried this action, but for some reason, the resulting `.zip` files [do not include a binary](https://github.com/joepio/atomic-data-rust/releases/tag/v0.25.3). Maybe I'm missing something in my configuration?

[see run](https://github.com/joepio/atomic-data-rust/actions/runs/1127029409)

[see workflow.yml](https://github.com/joepio/atomic-data-rust/blob/master/.github/workflows/release.yml)

**Comment by Douile** [comment]
Thanks for the report, the error produced by the workflow was
 ```
error: manifest path `/github/workspace/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```
You should be able to get around this by using the `SRC_DIR` environment variable to specify which sub-package (i can't remember exact rust terminology) to build e.g. `SRC_DIR: cli`

**Comment by joepio** [comment]
Thanks, you're right.

I basically forgot to add a `checkout` step:

```yml
      - uses: actions/checkout@v2
```

Just as a suggestion: maybe show an error and let the job fail if there is no binary data to be found. Or are there usecases to let the build succeed if there is no binary with this action?
