### ISSUE TITLE
Provide build artifacts

### ISSUE THREAD

**Issue by joshmuente** [rust-build/rust-build.action#20]
Useful if you want to do something with the compiled files.
In my example I had to re-download a build file to create a PKGBUILD for it. It would be easier if the binaries and sha256sums were accessible as artifacts in the workflow.

https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

**Comment by Douile** [comment]
The artifacts are uploaded to the release

**Comment by joshmuente** [comment]
i mean workflow artefacts. So that one can use the data in the workflow. Currently you have to download the data from the release if you want to use it in another workflow step/job.
