### ISSUE TITLE
I can't use this action to build macosx package

### ISSUE THREAD

**Issue by mrxiaozhuox** [rust-build/rust-build.action#21]
<img width="954" alt="截屏2021-09-26 下午7 48 26" src="https://user-images.githubusercontent.com/41265098/134806597-21aacf45-7391-44d1-a8c3-668e540860fd.png">

**Comment by Douile** [comment]
Could you provide a link to the full build log?

**Comment by mrxiaozhuox** [comment]
https://github.com/mrxiaozhuox/dorea/runs/3712671758?check_suite_focus=true

**Comment by mrxiaozhuox** [comment]
> Could you provide a link to the full build log?

I don't know how to fix it.

**Comment by Douile** [comment]
looks like one of the build scripts for a dependency fail. I am looking into it.
