### ISSUE TITLE
macOS cross compiling issue "unrecognized option '-dynamic'"

### ISSUE THREAD

**Issue by bumi** [rust-build/rust-build.action#36]
When trying to compile for macOS my build script fails. 
It works fine for Windows + Linux and I can also build it directly on my local macOS machine. 

Not sure if this is due to some incompatible dependency or if I am doing something wrong? 

```
error: linking with `/opt/osxcross/target/bin/x86_64-apple-darwin14-clang` failed: exit status: 1

[...]

 = note: /usr/bin/ld: unrecognized option '-dynamic'
          /usr/bin/ld: use the --help option for usage information
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `hyper` due to previous error
```

Full log: https://github.com/getAlby/alby-companion-rs/runs/4815937187?check_suite_focus=true
Sadly I don't know how to debug more.

**Comment by Douile** [comment]
Confirmed by https://github.com/rust-build/rust-build.test/runs/4818430928?check_suite_focus=true this is for any build for darwin, not related to the dependencies. Seems to have been introduced by the latest release v1.2.5

**Comment by bumi** [comment]
ok, thanks for confirming. 
I tried to use an older version: https://github.com/getAlby/alby-companion-rs/runs/4819219643?check_suite_focus=true#step:4:1 (not sure if I am doing that right) it fails there, too.

**Comment by Douile** [comment]
Yeah using old versions is broken #37

**Comment by Canvas02** [comment]
The problem is still happening to me:
https://github.com/Canvas02/paste_rs/runs/4827974263?check_suite_focus=true

**Comment by Douile** [comment]
@Canvas02 you need to wait for this to be included in a release

**Comment by BlackYoup** [comment]
Hello,

Thanks for the fix! Until a new release gets out, I've put this script as a PRE_BUILD script to patch the `build.sh` file:
```bash
#!/bin/sh

echo "Running pre-build script"
sed '/^export CXX.*/a export PATH="/opt/osxcross/target/bin:$PATH"\nexport LIBZ_SYS_STATIC=1' -i /build.sh
```

I guess you could also download it directly from Github, didn't think of that before :grin:

**Comment by bumi** [comment]
awesome, thanks for this fix. 
I get passed this problem now. but still have an issue:
https://github.com/getAlby/alby-companion-rs/runs/4865566671?check_suite_focus=true

Do you know maybe if that's an app issue? I can compile it on my macOS though.

**Comment by bumi** [comment]
true, makes sense. thanks a lot!! (I am pretty new to these Rust builds)

**Comment by MH4GF** [comment]
@BlackYoup thanks your patch!! it works for me! 

https://github.com/MH4GF/gh-prj/commit/f3e910c8f301801cbe23551cdb639823e5cd0c9a
https://github.com/MH4GF/gh-prj/actions/runs/1718334244
