### ISSUE TITLE
Is it possible to use this action without uploading an artifact?

### ISSUE THREAD

**Issue by JasonShin** [rust-build/rust-build.action#43]
I want to streamline my CI pipeline so that release and build uses the same action. I'm seeing a failure in CI if I don't provide GITHUB_TOKEN `Error: The event provided did not contain an upload URL, this workflow can only be used with the release event.`.

Please let me know if we can use this action without uploading artifacts, thanks

**Comment by Douile** [comment]
Duplicate of #20

**Comment by JasonShin** [comment]
@Douile Hey, not sure if this is a duplicate of that issue you linked. I'm wondering if we can make this action to be used without attaching artifacts to a release

**Comment by Douile** [comment]
True, marked duplicate as I want to make one unified setting:
`UPLOAD_MODE` one of `release` | `artifact` | `none` to control this, however none can be added a lot more easily.
