### ISSUE TITLE
Pre-Build script not running

### ISSUE THREAD

**Issue by AliSajid** [rust-build/rust-build.action#51]
Hi,

Thank you for this action. It has been very helpful. However, I recently migrated to using semantic release to automatically creating my releases and have had the same trouble as #46 . I am using a work around for that that uses a pre-build script but that script doesn't appear to run.

The repo I'm running this on is [AliSajid/iptmnet_client](https://github.com/AliSajid/iptmnet_client) and the workflow is in `.github/workflows/release.yaml`. The pre-build script is in `meta/pre-build.sh`.

**Comment by larsnaesbye** [comment]
Yes, I have the same problem. I even added a echo line to scream out whether we hit the script, and it doesn't activate.

**Comment by larsnaesbye** [comment]
Ah. It needs to be quoted to run.

**Comment by AliSajid** [comment]
Following @larsnaesbye , I quoted it and it works. Thank you.
