### ISSUE TITLE
Unable to pull v1.4.2 image

### ISSUE THREAD

**Issue by ratosh** [rust-build/rust-build.action#62]
I'm unable to build my since v1.4.2 release. Latest working version for me was v1.4.0 (used two weeks ago). Error log:
```
Pull down action image 'ghcr.io/rust-build/rust-build.action:v1.4.2'
  /usr/bin/docker pull ghcr.io/rust-build/rust-build.action:v1.4.2
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 3.07 seconds before retry.
  /usr/bin/docker pull ghcr.io/rust-build/rust-build.action:v1.4.2
  Error response from daemon: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 8.3 seconds before retry.
  /usr/bin/docker pull ghcr.io/rust-build/rust-build.action:v1.4.2
  Error response from daemon: manifest unknown
Error: Docker pull failed with exit code 1
```
If you wanna check the full lock log check here:
https://github.com/ratosh/caninana/actions/runs/4019945606

**Comment by Douile** [comment]
build failed https://github.com/rust-build/rust-build.action/actions/runs/4005106106

**Comment by ratosh** [comment]
Would rerun the job fix it?

**Comment by Douile** [comment]
No the action itself needs to be fixed used 1.4.0 for now

**Comment by timrogers** [comment]
Thank you so much for this great project ❤️ Do the maintainers have any intention of fixing 1.4.2? It's pretty confusing to have a version shipped with the Docker image missing.

**Comment by Douile** [comment]
my bad there was a fixed version months ago just never got released. 1.4.1, and 1.4.2 will remain broken but 1.4.3 will work.
