### ISSUE TITLE
Larger binary file than normal build

### ISSUE THREAD

**Issue by DiscreteTom** [rust-build/rust-build.action#69]
Thanks for this cool lib!

On my Windows PC, calling `cargo build` or `cargo build --release` will yield a file smaller than 5MB. But with this action, the binary is larger than 10MB.

Here is my project and the build: https://github.com/DiscreteTom/shremdup/releases/tag/v0.1.3

In v0.1.4 I use UPX to minify the binary, but Windows Defender think the modified binary is a virus...

What is the reason that the binary is larger than normal build? Is there any other way to reduce the binary size?

**Comment by Douile** [comment]
So if you set `MINIFY` to true we will automatically strip the binary using UPX, otherwise not sure about size difference could be a result of building for windows using GCC on linux whereas you are building for windows on windows using Microsofts compiler.
