### ISSUE TITLE
darwin system support please

### ISSUE THREAD

**Issue by mrxiaozhuox** [rust-build/rust-build.action#7]
I think darwin( MacOS ) is very important. so please support it. 😄

**Comment by Douile** [comment]
I agree should be added. I will have a look

**Comment by Douile** [comment]
@mrxiaozhuox would you mind checking whether https://github.com/rust-build/rust-build.test/releases/tag/21 produced a valid darwin binary?

**Comment by mrxiaozhuox** [comment]
@Douile Thinks, I will try to use it in my project 😃
