### ISSUE TITLE
Rust curl 403 error

### ISSUE THREAD

**Issue by vschwaberow** [rust-build/rust-build.action#96]
Compiling of my rust project npwg works, but pushing the zip files seems to fail. Here are the last lines of the log. Can you help me to get into the right direction to fix this issue?

::info::Packing files: npwg.exe
  adding: npwg.exe (deflated 58%)
curl: (22) The requested URL returned error: 403
{"message":"Resource not accessible by integration","request_id":"B080:110608:333190:3E9338:661A041C","documentation_url":"https://docs.github.com/rest"}
##[debug]Docker Action run completed with exit code 22
##[debug]Set output BUILT_ARCHIVE = output/npwg_v0.1.2_x86_64-pc-windows-gnu.zip
##[debug]Set output BUILT_CHECKSUM = output/npwg_v0.1.2_x86_64-pc-windows-gnu.zip.sha256sum
##[debug]Finishing: Compile and release

**Comment by Douile** [comment]
Check your actions options on the repo. I'm pretty sure for this you need to allow actions to write (make changes) to the repo.

**Comment by vschwaberow** [comment]
Thanks that was it. Sometimes you can't see the wood for the trees.
